name: places
description: A new Flutter project.
organization: Evdokimov-sailing


publish_to: 'none' 

version: 1.0.0+1

environment:

  sdk: ">=2.17.3 < 3.7.0"


dependencies:
  flutter:
    sdk: flutter
    
  animated_button_bar: ^0.0.2
  provider: ^6.0.0
  flutter_svg: ^1.1.6
  fluttertoast: ^8.2.1
  


  
  
  cupertino_icons: ^1.0.2
  haversine_distance: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

  assets: 
    - lib/ui/res/images/
    - lib/ui/res/icons/
 
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts: 
        - asset: lib/fonts/Roboto/Roboto-Light.ttf
        - asset: lib/fonts/Roboto/Roboto-Black.ttf    

  